# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Desktop/2ASK_FPGA/2ASK-bandpass-system-transmitter/fpga_project/ASK/ASK.srcs/sources_1/ip/dds/dds.xci
# IP: The module: 'dds' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Desktop/2ASK_FPGA/2ASK-bandpass-system-transmitter/fpga_project/ASK/ASK.srcs/sources_1/ip/dds/dds_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Desktop/2ASK_FPGA/2ASK-bandpass-system-transmitter/fpga_project/ASK/ASK.srcs/sources_1/ip/dds/dds.xci
# IP: The module: 'dds' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Desktop/2ASK_FPGA/2ASK-bandpass-system-transmitter/fpga_project/ASK/ASK.srcs/sources_1/ip/dds/dds_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
